"""create normalized journal schema

Revision ID: 2741b21856ba
Revises: 
Create Date: 2026-07-23 17:16:15.977211
"""
from alembic import op
import sqlalchemy as sa

revision = '2741b21856ba'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_normalized_name'), 'tags', ['normalized_name'], unique=True)
    op.create_table('call_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_note_id'), 'call_events', ['note_id'], unique=False)
    op.create_table('note_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_note_id', sa.String(length=36), nullable=False),
    sa.Column('to_note_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['to_note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_relationships_from_note_id'), 'note_relationships', ['from_note_id'], unique=False)
    op.create_index(op.f('ix_note_relationships_to_note_id'), 'note_relationships', ['to_note_id'], unique=False)
    op.create_table('note_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'revision_number', name='uq_note_revision_number')
    )
    op.create_index(op.f('ix_note_revisions_note_id'), 'note_revisions', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_revisions_user_id'), 'note_revisions', ['user_id'], unique=False)
    op.create_table('note_security_mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('raw_token', sa.String(length=64), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_security_mentions_note_id'), 'note_security_mentions', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_security_mentions_security_id'), 'note_security_mentions', ['security_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.create_table('security_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('adjusted_price', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('price_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_prices_security_id'), 'security_prices', ['security_id'], unique=False)
    op.create_index('ix_security_prices_security_timestamp', 'security_prices', ['security_id', 'timestamp'], unique=False)
    op.create_table('tracked_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('originating_note_id', sa.String(length=36), nullable=False),
    sa.Column('call_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('benchmark_security_id', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_from_call_id', sa.String(length=36), nullable=True),
    sa.Column('closing_reason', sa.Text(), nullable=True),
    sa.Column('invalidation_category', sa.String(length=64), nullable=True),
    sa.Column('legacy_metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['originating_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['reversed_from_call_id'], ['tracked_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_calls_originating_note_id'), 'tracked_calls', ['originating_note_id'], unique=False)
    op.create_index(op.f('ix_tracked_calls_status'), 'tracked_calls', ['status'], unique=False)
    op.create_index(op.f('ix_tracked_calls_user_id'), 'tracked_calls', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('auth_provider', sa.String(length=64), nullable=False),
    sa.Column('auth_provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_benchmark_security_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_benchmark_security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('call_benchmark_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracked_call_id', sa.String(length=36), nullable=False),
    sa.Column('benchmark_security_id', sa.String(length=36), nullable=False),
    sa.Column('entry_price_raw', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_price_adjusted', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('entry_quote_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price_type', sa.String(length=32), nullable=False),
    sa.Column('entry_provider', sa.String(length=64), nullable=False),
    sa.Column('exit_price_raw', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_price_adjusted', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_quote_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price_type', sa.String(length=32), nullable=True),
    sa.Column('exit_provider', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['tracked_call_id'], ['tracked_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_benchmark_snapshots_tracked_call_id'), 'call_benchmark_snapshots', ['tracked_call_id'], unique=True)
    op.create_table('tracked_call_legs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracked_call_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('leg_order', sa.Integer(), nullable=False),
    sa.Column('entry_price_raw', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_price_adjusted', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('entry_quote_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price_type', sa.String(length=32), nullable=False),
    sa.Column('entry_market_session', sa.String(length=32), nullable=True),
    sa.Column('entry_provider', sa.String(length=64), nullable=False),
    sa.Column('entry_currency', sa.String(length=8), nullable=False),
    sa.Column('exit_price_raw', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_price_adjusted', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_quote_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price_type', sa.String(length=32), nullable=True),
    sa.Column('exit_provider', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['tracked_call_id'], ['tracked_calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracked_call_id', 'leg_order', name='uq_call_leg_order')
    )
    op.create_index(op.f('ix_tracked_call_legs_security_id'), 'tracked_call_legs', ['security_id'], unique=False)
    op.create_index(op.f('ix_tracked_call_legs_tracked_call_id'), 'tracked_call_legs', ['tracked_call_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_call_legs_tracked_call_id'), table_name='tracked_call_legs')
    op.drop_index(op.f('ix_tracked_call_legs_security_id'), table_name='tracked_call_legs')
    op.drop_table('tracked_call_legs')
    op.drop_index(op.f('ix_call_benchmark_snapshots_tracked_call_id'), table_name='call_benchmark_snapshots')
    op.drop_table('call_benchmark_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracked_calls_user_id'), table_name='tracked_calls')
    op.drop_index(op.f('ix_tracked_calls_status'), table_name='tracked_calls')
    op.drop_index(op.f('ix_tracked_calls_originating_note_id'), table_name='tracked_calls')
    op.drop_table('tracked_calls')
    op.drop_index('ix_security_prices_security_timestamp', table_name='security_prices')
    op.drop_index(op.f('ix_security_prices_security_id'), table_name='security_prices')
    op.drop_table('security_prices')
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_note_security_mentions_security_id'), table_name='note_security_mentions')
    op.drop_index(op.f('ix_note_security_mentions_note_id'), table_name='note_security_mentions')
    op.drop_table('note_security_mentions')
    op.drop_index(op.f('ix_note_revisions_user_id'), table_name='note_revisions')
    op.drop_index(op.f('ix_note_revisions_note_id'), table_name='note_revisions')
    op.drop_table('note_revisions')
    op.drop_index(op.f('ix_note_relationships_to_note_id'), table_name='note_relationships')
    op.drop_index(op.f('ix_note_relationships_from_note_id'), table_name='note_relationships')
    op.drop_table('note_relationships')
    op.drop_index(op.f('ix_call_events_note_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_tags_normalized_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
