"""Sprint 1 expectations, thesis details, and read-only portfolio snapshots."""
from alembic import op
import sqlalchemy as sa
revision = "8f1a2b3c4d5e"
down_revision = "7c9d2e5f1a31"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("thesis_details", sa.Column("id", sa.String(36), primary_key=True), sa.Column("note_id", sa.String(36), sa.ForeignKey("notes.id"), nullable=False, unique=True), sa.Column("core_thesis", sa.Text), sa.Column("key_evidence_json", sa.JSON), sa.Column("catalysts_json", sa.JSON), sa.Column("risks_json", sa.JSON), sa.Column("invalidation_conditions_json", sa.JSON), sa.Column("valuation_notes", sa.Text), sa.Column("expected_time_horizon_days", sa.Integer), sa.Column("review_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("call_expectations", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tracked_call_id", sa.String(36), sa.ForeignKey("tracked_calls.id"), nullable=False), sa.Column("target_type", sa.String(32), nullable=False), sa.Column("target_value", sa.Numeric(18,6)), sa.Column("target_unit", sa.String(16)), sa.Column("expected_return", sa.Numeric(18,6)), sa.Column("time_horizon_days", sa.Integer), sa.Column("review_at", sa.DateTime(timezone=True)), sa.Column("catalyst_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("brokerage_connections", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), nullable=False), sa.Column("provider", sa.String(32), nullable=False), sa.Column("display_name", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("last_synced_at", sa.DateTime(timezone=True)), sa.Column("metadata_json", sa.JSON), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("brokerage_accounts", sa.Column("id", sa.String(36), primary_key=True), sa.Column("connection_id", sa.String(36), sa.ForeignKey("brokerage_connections.id"), nullable=False), sa.Column("external_account_id_hash", sa.String(128), nullable=False), sa.Column("display_name", sa.String(255), nullable=False), sa.Column("account_type", sa.String(64)), sa.Column("base_currency", sa.String(8), nullable=False), sa.Column("active", sa.Boolean), sa.Column("last_synced_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("connection_id", "external_account_id_hash", name="uq_brokerage_account_external"))
    op.create_table("portfolio_positions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("brokerage_account_id", sa.String(36), sa.ForeignKey("brokerage_accounts.id"), nullable=False), sa.Column("security_id", sa.String(36), sa.ForeignKey("securities.id"), nullable=False), sa.Column("external_contract_id", sa.String(128)), sa.Column("quantity", sa.Numeric(20,6), nullable=False), sa.Column("average_cost", sa.Numeric(20,6)), sa.Column("market_price", sa.Numeric(20,6)), sa.Column("market_value", sa.Numeric(20,6)), sa.Column("unrealized_pnl", sa.Numeric(20,6)), sa.Column("realized_pnl", sa.Numeric(20,6)), sa.Column("currency", sa.String(8), nullable=False), sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False), sa.Column("metadata_json", sa.JSON))
def downgrade():
    op.drop_table("portfolio_positions"); op.drop_table("brokerage_accounts"); op.drop_table("brokerage_connections"); op.drop_table("call_expectations"); op.drop_table("thesis_details")
