"""Sprint 3 inbox and source provenance."""
from alembic import op
import sqlalchemy as sa
revision='a1b2c3d4e5f6';down_revision='9a2b3c4d5e6f';branch_labels=depends_on=None
def upgrade():
 op.create_table('sources',sa.Column('id',sa.String(36),primary_key=True),sa.Column('user_id',sa.String(36),nullable=False),sa.Column('source_type',sa.String(32),nullable=False),sa.Column('external_id',sa.String(255)),sa.Column('canonical_url',sa.String(2000)),sa.Column('original_url',sa.String(2000)),sa.Column('title',sa.String(500)),sa.Column('raw_content',sa.Text),sa.Column('cleaned_content',sa.Text),sa.Column('excerpt',sa.Text),sa.Column('content_status',sa.String(20),nullable=False),sa.Column('metadata_json',sa.JSON),sa.Column('captured_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('user_id','source_type','external_id',name='uq_source_external'))
 op.create_table('inbox_items',sa.Column('id',sa.String(36),primary_key=True),sa.Column('user_id',sa.String(36),nullable=False),sa.Column('item_type',sa.String(32),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('channel',sa.String(32),nullable=False),sa.Column('title',sa.String(500)),sa.Column('raw_text',sa.Text),sa.Column('source_id',sa.String(36),sa.ForeignKey('sources.id')),sa.Column('external_id',sa.String(255)),sa.Column('received_at',sa.DateTime(timezone=True)),sa.Column('processed_at',sa.DateTime(timezone=True)),sa.Column('idempotency_key',sa.String(128)),sa.Column('metadata_json',sa.JSON),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('user_id','channel','external_id',name='uq_inbox_external'),sa.UniqueConstraint('user_id','idempotency_key',name='uq_inbox_idempotency'))
 op.create_table('note_sources',sa.Column('note_id',sa.String(36),sa.ForeignKey('notes.id'),primary_key=True),sa.Column('source_id',sa.String(36),sa.ForeignKey('sources.id'),primary_key=True),sa.Column('relationship_type',sa.String(32)),sa.Column('excerpt',sa.Text),sa.Column('created_at',sa.DateTime(timezone=True)))
def downgrade(): op.drop_table('note_sources');op.drop_table('inbox_items');op.drop_table('sources')
